version: 0.5.0.{build}
image: Visual Studio 2017 Preview
branches:
  only:
  - master
before_build:
- nuget restore
build_script:
- cmd: build.cmd
test: off
artifacts:
- path: artifacts\*.nupkg
  name: Nuget