version: 0.5.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master
before_build:
- nuget restore
build:
  project: build\build.proj
  verbosity: normal
test: off
artifacts:
- path: artifacts\*.nupkg
  name: Nuget